### ISSUE TITLE
deps里缺乏文件

### ISSUE THREAD

**Issue by jwma2012** [SJTU-IPADS/wukong#1]
您好，我是一名高校研究生，在安装wukong的时候，发现deps里缺少文件librdma-1.0.0.tar.gz

**Comment by realstolz** [comment]
Wukong provides a script (deps.sh) to help install all deps, which will download files (incl. librdma-1.0.0.tar.gz) and install them in your deps/ directory. If you want to do it by yourself, you could download the file from "http://ipads.se.sjtu.edu.cn/wukong/librdma-1.0.0.tar.gz" and follow the steps listed in deps/INSTALL.md.

**Comment by jwma2012** [comment]
Thank you very much!

**Comment by cyfdecyf** [comment]
@realstolz The link to librdma now requires login. Could you please fix the link?

**Comment by cyfdecyf** [comment]
@realstolz Found a version from here https://github.com/Mogami95/RDMA-Playground/blob/master/WK-COMM/librdma-1.0.0.tar.gz

**Comment by wxdwfc** [comment]
The library has been extracted to the source of Wukong and is no longer need to download. The standalone version of the library has been moved to: https://github.com/wxdwfc/rlibv2 .

**Comment by cyfdecyf** [comment]
@wxdwfc Thanks! Guess Wukong's doc [deps/INSTALL.md](https://ipads.se.sjtu.edu.cn:1312/opensource/wukong/-/blob/bc5c121c91afa5d23dcecded707ef6097abf8ba5/deps/INSTALL.md) should be updated.
