### ISSUE TITLE
wukong是使用什么存储rdf数据的？

### ISSUE THREAD

**Issue by jinandan** [SJTU-IPADS/wukong#12]
你好！请问wukong是使用什么来存储rdf数据的？

**Comment by realstolz** [comment]
Wukong stores RDF data on a distributed key/value store.

Paper: Fast and concurrent RDF queries with RDMA-based distributed graph exploration.
https://github.com/SJTU-IPADS/wukong/blob/master/docs/papers/wukong-osdi16.pdf
