### ISSUE TITLE
增量更新

### ISSUE THREAD

**Issue by yuinm** [SJTU-IPADS/wukong#13]
您好， 我看到wukong里面有DynamicGStore, 这个提供的功能是不是支持图关系的动态更新啊？

**Comment by realstolz** [comment]
dynamic gstore支持动态更新图数据（append），并提供了简单的命令行接口。
https://github.com/SJTU-IPADS/wukong/blob/master/docs/COMMANDS.md#load-graph-data-into-dynamic-graph-store

更多功能可以通过代码扩展完成（目前还没有在github开源）

**Comment by yuinm** [comment]
哦哦， 好的，谢谢您， 我去研究研究
