### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by fengfan237** [SJTU-IPADS/wukong#14]
您好，我按照步骤装好依赖后，没有对连通各个节点，只在自己主机上编译。然后出现了一个问题，显示找不到mpic++这个工具。
The CMAKE_CXX_COMPILER:

    /root/ff/wukong/deps/openmpi-1.6.5-install/bin/mpic++

  is not a full path to an existing compiler tool.
这是报错原话，我在bin目录下也找不到mpic++这个文件，请问这是怎么回事，求解答

**Comment by realstolz** [comment]
看着是 mpi 安装失败了，deps里面单独重新安装mpi

**Comment by fengfan237** [comment]
好的谢谢您，我也试过单独安装了很多次，有可能是配置出了问题，mpi没安装好，我再仔细看下，麻烦您了

**Comment by fengfan237** [comment]
请问这个项目可以单机运行吗？不使用rdma和hdfs，单机能够使用GPU进行测试吗？

**Comment by realstolz** [comment]
hdfs是可选的，单击可以不使用rdma。 支持GPU和单机/分布式允许没有关系。
