### ISSUE TITLE
您好，代码无法运行

### ISSUE THREAD

**Issue by DittoWii** [SJTU-IPADS/wukong#15]
您好，我在使用wukong测试例子：tests/gpu/test-adaptor.cpp的时候。
如果使用GPU，会在RDMA_init函数里边停止运行，报错为Connect Device Memory Region failed at dev 0, err Bad address；
如果不使用GPU，将代码改为纯CPU的话，则会在send函数报错，got bad completion with status: 0xc, vendor syndrome: 0x81, with error transport retry counter exceeded, qp n:2 t:0；
特别是第二个问题，网上信息较少，请问应该如何解决？
十分感谢！望回复。

**Comment by EsdeathYZH** [comment]
可以尝试重启RDMA服务

**Comment by DittoWii** [comment]
您好，我在尝试短时间内多次运行代码的时候出现TCP端口无法释放，提示Address already in use。现在每次运行都要手动改RDMA_CTRL_PORT的值，请问应该如何解决？十分感谢，万望回复！

**Comment by wxdwfc** [comment]
您好，
在wukong/rdma_lib/rdmaio.hpp:1160行，
将`setsockopt(listenfd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(int)`改成
`setsockopt(listenfd,SOL_SOCKET,SO_REUSEADDR | SO_REUSEPORT,&opt,sizeof(int)`
应该就能fix这个问题。
