### ISSUE TITLE
关于query分发

### ISSUE THREAD

**Issue by PrincessLiu** [SJTU-IPADS/wukong#6]
![d7c0771e-aef1-4327-be6b-b8468dd838cc](https://user-images.githubusercontent.com/19248708/47342476-658ec180-d6d6-11e8-9846-3f318a16fd18.jpeg)
query分发在代码中只体现为根据subject，似乎根据论文还应该有根据predicate和object的分发，是实现时有修改还是我漏看了哪部分代码？烦请指教

**Comment by realstolz** [comment]
经过Parser/Planner处理之后  get_start返回的是 subject/object 取决于执行方向，并非一定返回subject。至于predicate，wukong使用 differentiate partition，index（predicate/type）是在所有机器上分布的，predicate index出发的任务是发到所有机器上并行执行的（fork-join模式）。这个处理是和论文上一致的。

**Comment by realstolz** [comment]
有一点区别是，任何一个request都是先发送给一个engine，然后这个engine判断是否需要 multithread（一台机器里面几个thread参与）和fork-join（所有机器参与）
参见：bool execute_patterns(SPARQLQuery &r)

这个比paper里面的方式（假设proxy知道，如果是fork-join，proxy会发很多个request）要更通用一些，但是可能会多一个message。
