### ISSUE TITLE
关于wukong系统查询相关问题

### ISSUE THREAD

**Issue by PrincessLiu** [SJTU-IPADS/wukong#7]
在proxy.hpp中run_single_query函数最后几行，代码段为
            send_request(request);
            reply = recv_reply();
第一条代码实际执行了将分解后的查询分发到各个对应的节点，第二条代码是各个节点监听是否收到消息，如果收到消息且是查询，就把查询赋值给reply。然后这个函数最后参数中的reply对应的是最后一次字查询的reply。
但是并没有找到实际执行查询的过程，即从vector中查找符合要求的项。
想知道wukong系统中实际执行查询是在哪一部分？
另外wukong底层存储spo或者ops是按照三元组有序存储的，基于主语或者宾语的查询是否是采用类似于的快速搜索这种搜索算法？

**Comment by realstolz** [comment]
按照wukong的架构，分成proxy和engine，proxy（运行console）负责发送sparql query给engine，engine负责执行具体的sparql query。你要看执行，在engine.hpp

wukong存储不是用三元组，采用graph model，底层实现是kvstore。设计可以见paper，存储（gstore）代码在 dgraph.hpp和gstore.hpp。因为kvstore存储（hash），lookup是使用hash，但是wukong采用的vertex decomposition设计（见paper的predicate-based store），所以hash的输入有 subject/object+predicate+direction构成。

**Comment by PrincessLiu** [comment]
谢谢老师，请问RoCE版本的代码现在合起来了吗？

**Comment by realstolz** [comment]
wukong使用的rdma-lib已经完成了RoCE的支持，用在了我们另一个项目DrTM+H上（OSDI 2018）。我们正在wukong上移植新的rdma-lib实现，会很快完成。但可能需要更多的时间等wukong其他部分的实现相对稳定后，才会push到github的repo上
