### ISSUE TITLE
编译失败，cannot find -libverbs

### ISSUE THREAD

**Issue by lionty** [SJTU-IPADS/wukong#9]
您好！我在编译wukong的时候遇到了问题。因为我的服务器不支持rdma，所以我使用./build.sh  -DUSE_RDMA=OFF命令编译。但是出现了以下的问题。麻烦您有空解答一下。谢谢！
root@node6:/usr/data/pikachu_test/app_install_by_src/wukong-master/scripts# ./build.sh  -DUSE_RDMA=OFF
options:   -DUSE_RDMA=OFF
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/data/pikachu_test/app_install_by_src/wukong-master/build
Scanning dependencies of target wukong
[ 50%] Building CXX object CMakeFiles/wukong.dir/core/wukong.cpp.o
[100%] Linking CXX executable wukong
/usr/bin/ld: cannot find -libverbs
collect2: error: ld returned 1 exit status
CMakeFiles/wukong.dir/build.make:97: recipe for target 'wukong' failed
make[2]: *** [wukong] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wukong.dir/all' failed
make[1]: *** [CMakeFiles/wukong.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aswasn** [comment]
In `CMakeLists.txt`, remove `ibverbs` in line `set(WUKONG_LIBS ${WUKONG_LIBS} zmq rt ibverbs tbb hwloc)`.
We will fix the problem in later release.

**Comment by realstolz** [comment]
The new version (v0.2.0) has fixed the issue.
